#!/usr/bin/env bash
# =============================================================================
# setup_staging.sh — Railway Staging Environment Reference Guide
# =============================================================================
#
# SESSION A: STAGING ENVIRONMENT SETUP
#
# This script is a REFERENCE GUIDE with comments, not an auto-provisioner.
# Run the steps manually in the Railway dashboard or via the Railway CLI.
#
# Staging URL: https://sfpermits-ai-staging.up.railway.app
# =============================================================================

set -euo pipefail

echo "=================================================================="
echo "  sfpermits.ai — Staging Environment Setup Guide"
echo "=================================================================="
echo ""
echo "STEP 1: Create the staging service in Railway"
echo "  - Go to your Railway project: sfpermits-ai"
echo "  - Click 'New Service' -> 'GitHub Repo'"
echo "  - Select: tbrennem-source/sf-permits-mcp"
echo "  - Set branch: main (or a staging branch if you prefer)"
echo "  - Name the service: sfpermits-ai-staging"
echo ""
echo "STEP 2: Connect to pgvector-db"
echo "  - In the staging service settings, add a reference variable:"
echo "    DATABASE_URL = \${{pgvector-db.DATABASE_URL}}"
echo "  - Or use a separate staging DB (recommended for isolation)"
echo ""
echo "STEP 3: Generate TEST_LOGIN_SECRET"
echo "  Run this command to generate a secure secret:"
echo ""
echo "    python3 -c \"import secrets; print(secrets.token_urlsafe(32))\""
echo ""
echo "  Copy the output — you'll need it for RELAY scripts."
echo ""
echo "STEP 4: Set required environment variables on sfpermits-ai-staging"
echo ""
echo "  REQUIRED (staging-specific):"
echo "    ENVIRONMENT=staging"
echo "    TESTING=true"
echo "    TEST_LOGIN_SECRET=<output from step 3>"
echo ""
echo "  REQUIRED (same as production):"
echo "    DATABASE_URL=<pgvector-db internal URL or staging DB>"
echo "    FLASK_SECRET_KEY=<generate with: python3 -c \"import secrets; print(secrets.token_hex(32))\">"
echo "    CRON_SECRET=<same as prod>"
echo "    ADMIN_EMAIL=<your email>"
echo "    ANTHROPIC_API_KEY=<same as prod>"
echo "    OPENAI_API_KEY=<same as prod>"
echo ""
echo "  OPTIONAL (same as prod if email needed):"
echo "    SMTP_HOST=<same as prod>"
echo "    SMTP_PORT=587"
echo "    SMTP_FROM=<same as prod>"
echo "    SMTP_USER=<same as prod>"
echo "    SMTP_PASS=<same as prod>"
echo "    BASE_URL=https://sfpermits-ai-staging.up.railway.app"
echo "    BRAND_NAME=sfpermits.ai [STAGING]"
echo "    INVITE_CODES=<comma-separated codes if needed>"
echo ""
echo "STEP 5: NEVER set these on production:"
echo "    TESTING       — enables /auth/test-login endpoint"
echo "    TEST_LOGIN_SECRET — the test login shared secret"
echo ""
echo "STEP 6: Verify staging is running"
echo "  After deploy (~2 min):"
echo "    curl -s https://sfpermits-ai-staging.up.railway.app/health | python3 -m json.tool"
echo ""
echo "STEP 7: Run RELAY QA"
echo "  Use the QA script: qa-drop/session-a-staging-qa.md"
echo "  Set E2E_BASE_URL=https://sfpermits-ai-staging.up.railway.app"
echo "  Set TEST_LOGIN_SECRET=<value from step 3>"
echo ""
echo "=================================================================="
echo "  SECURITY NOTES"
echo "=================================================================="
echo ""
echo "  - TESTING + TEST_LOGIN_SECRET bypass email auth — treat as credentials"
echo "  - Rotate TEST_LOGIN_SECRET if it leaks"
echo "  - Staging should use a separate DB from prod if data isolation needed"
echo "  - The /auth/test-login endpoint returns 404 on prod (TESTING not set)"
echo ""
echo "=================================================================="
